In [62]:
import pandas as pd
from numpy import mean

# read from data set
df =  pd.read_csv('Laterality.csv')
df.head()

Number seizure_Simiology_Laterality Laterality_ictal_EEG  \
0       1                            L                    L   
1       2                            L                    L   
2       3                            U                   UL   
3       4                            U                   UL   
4       5                            U                    R   

  ictal_Epileptogenic_zone interictal_irritative_zone MRI_findings  \
0                        L                         UL            L   
1                        L                         UR            L   
2                        L                          U           UR   
3                        L                         UL            L   
4                        R                          R            R   

   Hipp_Vol_LI hippocampal volume  Hipp_FLAIR_LI FLAIR signal intensity  ...  \
0    -0.050890                 UL      -0.212758                      L  ...   
1    -0.084469                  L      -0.326595                      L  ...   
2    -0.000530                  U       0.266374                      R  ...   
3    -0.082927                  L      -0.524212                      L  ...   
4    -0.007018                  U       0.239003                      R  ...   

   FA cingulum   Fx_LI  FA fornix  Hipp_MD_LI  hippMD Logistic prediction  \
0           UR  0.0506           R  -0.000163       L                   L   
1            L  0.0208          UR  -0.000138       L                   L   
2           UL -0.0379           L  -0.000024      UL                   U   
3            L -0.0175          UL  -0.000362       L                   L   
4           UL  0.0551           R   0.000176       R                   R   

  Side_ C4.5 Decision Tree Handedness  gender Overall_Laterality_NO  
0                        L          L  female                     0  
1                        L          R  female                     0  
2                        L          R  female                     0  
3                        L          R    male                     0  
4                        R          R    male                     1  

[5 rows x 21 columns]

In [63]:
df.describe()

Number  Hipp_Vol_LI  Hipp_FLAIR_LI      Cg_LI      Fx_LI  \
count  35.000000    35.000000      35.000000  35.000000  35.000000   
mean   17.742857    -0.016640      -0.097719  -0.032931   0.013771   
std    10.062577     0.061620       0.267247   0.046677   0.033438   
min     1.000000    -0.129227      -0.558875  -0.140300  -0.046900   
25%     9.500000    -0.063088      -0.325745  -0.060300  -0.013550   
50%    18.000000    -0.017164      -0.073292  -0.031900   0.020600   
75%    25.500000     0.007082       0.079581  -0.001750   0.042000   
max    36.000000     0.106508       0.499853   0.080900   0.071600   

       Hipp_MD_LI  Overall_Laterality_NO  
count   35.000000              35.000000  
mean    -0.000054               0.371429  
std      0.000189               0.490241  
min     -0.000765               0.000000  
25%     -0.000141               0.000000  
50%     -0.000024               0.000000  
75%      0.000042               1.000000  
max      0.000284               1.000000

In [64]:
print(df.columns)
#sprate label from data
label = df['Overall_Laterality_NO']
del df['Overall_Laterality_NO']

Index(['Number', 'seizure_Simiology_Laterality', 'Laterality_ictal_EEG',
       'ictal_Epileptogenic_zone', 'interictal_irritative_zone',
       'MRI_findings', 'Hipp_Vol_LI', 'hippocampal volume', 'Hipp_FLAIR_LI',
       'FLAIR signal intensity', 'Cg_LI', 'FA cingulum', 'Fx_LI', 'FA fornix ',
       'Hipp_MD_LI', 'hippMD', 'Logistic prediction',
       'Side_ C4.5 Decision Tree', 'Handedness', 'gender',
       'Overall_Laterality_NO'],
      dtype='object')


In [65]:
df = df.replace(to_replace=["L"],value=int(2))
# Lift equal to 2
df = df.replace(to_replace=["UL"],value=int(1))
# near left 1
df = df.replace(to_replace=["R"],value=-int(-2))
# Right -2
df = df.replace(to_replace=["UR"],value=int(-1))
# near Right -1
df = df.replace(to_replace=["U"],value=int(0))
# in center 0
df = df.replace(to_replace=["female"],value=int(-1))
# female -1
df = df.replace(to_replace=["male"],value=int(1))
# male +1
df = df.replace(to_replace=["Both"],value=int(0))
# both 0
df.head()


Number  seizure_Simiology_Laterality  Laterality_ictal_EEG  \
0       1                             2                     2   
1       2                             2                     2   
2       3                             0                     1   
3       4                             0                     1   
4       5                             0                     2   

   ictal_Epileptogenic_zone  interictal_irritative_zone  MRI_findings  \
0                         2                           1             2   
1                         2                          -1             2   
2                         2                           0            -1   
3                         2                           1             2   
4                         2                           2             2   

   Hipp_Vol_LI  hippocampal volume  Hipp_FLAIR_LI  FLAIR signal intensity  \
0    -0.050890                   1      -0.212758                       2   
1    -0.084469                   2      -0.326595                       2   
2    -0.000530                   0       0.266374                       2   
3    -0.082927                   2      -0.524212                       2   
4    -0.007018                   0       0.239003                       2   

    Cg_LI  FA cingulum   Fx_LI  FA fornix   Hipp_MD_LI  hippMD  \
0  0.0296           -1  0.0506           2   -0.000163       2   
1 -0.1032            2  0.0208          -1   -0.000138       2   
2 -0.0255            1 -0.0379           2   -0.000024       1   
3 -0.0506            2 -0.0175           1   -0.000362       2   
4 -0.0165            1  0.0551           2    0.000176       2   

   Logistic prediction  Side_ C4.5 Decision Tree  Handedness  gender  
0                    2                         2           2      -1  
1                    2                         2           2      -1  
2                    0                         2           2      -1  
3                    2                         2           2       1  
4                    2                         2           2       1

In [66]:
list_col_new = ['Number']
list_col = ['seizure_Simiology_Laterality', 'Laterality_ictal_EEG',
            'ictal_Epileptogenic_zone', 'interictal_irritative_zone',
            'MRI_findings','hippocampal volume','FLAIR signal intensity',
            'FA cingulum','FA fornix ',
            'hippMD' , 'Logistic prediction', 'Side_ C4.5 Decision Tree']

# make one hot conding for catorical feature
for name in list_col:
        df[f"L_{name}"] = df[f"{name}"] == 2
        list_col_new.append("L_{name}")

        df[f"UL_{name}"] = df[f"{name}"] == 1
        list_col_new.append(f"UL_{name}")

        df[f"R_{name}"] = df[f"{name}"] == -2
        list_col_new.append(f"R_{name}")

        df[f"UR_{name}"] = df[f"{name}"] == -1
        list_col_new.append(f"UR_{name}")

        df[f"U_{name}"] = df[f"{name}"] == 0
        list_col_new.append(f"U_{name}")

        del df[f'{name}']


df["female"] =  df["gender"] == -1
df["male"] =  df["gender"] == +1
df["Both"] =  df["gender"] == 0

In [67]:
df.head()



Number  Hipp_Vol_LI  Hipp_FLAIR_LI   Cg_LI   Fx_LI  Hipp_MD_LI  gender  \
0       1    -0.050890      -0.212758  0.0296  0.0506   -0.000163      -1   
1       2    -0.084469      -0.326595 -0.1032  0.0208   -0.000138      -1   
2       3    -0.000530       0.266374 -0.0255 -0.0379   -0.000024      -1   
3       4    -0.082927      -0.524212 -0.0506 -0.0175   -0.000362       1   
4       5    -0.007018       0.239003 -0.0165  0.0551    0.000176       1   

   L_seizure_Simiology_Laterality  UL_seizure_Simiology_Laterality  \
0                            True                            False   
1                            True                            False   
2                           False                            False   
3                           False                            False   
4                           False                            False   

   R_seizure_Simiology_Laterality  ...  R_Side_ C4.5 Decision Tree  \
0                           False  ...                       False   
1                           False  ...                       False   
2                           False  ...                       False   
3                           False  ...                       False   
4                           False  ...                       False   

   UR_Side_ C4.5 Decision Tree  U_Side_ C4.5 Decision Tree  L_Handedness  \
0                        False                       False          True   
1                        False                       False          True   
2                        False                       False          True   
3                        False                       False          True   
4                        False                       False          True   

   UL_Handedness  R_Handedness  UR_Handedness  U_Handedness  female   male  
0          False         False          False         False    True  False  
1          False         False          False         False    True  False  
2          False         False          False         False    True  False  
3          False         False          False         False   False   True  
4          False         False          False         False   False   True  

[5 rows x 74 columns]

In [68]:
# new_col = [p for p in df.columns if p not in list_col_new]
# for column in new_col:
#         df[column] = (df[column] - df[column].mean()) / df[column].std()
# df.head()


In [69]:
df.describe()

Number  Hipp_Vol_LI  Hipp_FLAIR_LI      Cg_LI      Fx_LI  \
count  35.000000    35.000000      35.000000  35.000000  35.000000   
mean   17.742857    -0.016640      -0.097719  -0.032931   0.013771   
std    10.062577     0.061620       0.267247   0.046677   0.033438   
min     1.000000    -0.129227      -0.558875  -0.140300  -0.046900   
25%     9.500000    -0.063088      -0.325745  -0.060300  -0.013550   
50%    18.000000    -0.017164      -0.073292  -0.031900   0.020600   
75%    25.500000     0.007082       0.079581  -0.001750   0.042000   
max    36.000000     0.106508       0.499853   0.080900   0.071600   

       Hipp_MD_LI     gender  
count   35.000000  35.000000  
mean    -0.000054  -0.028571  
std      0.000189   1.014185  
min     -0.000765  -1.000000  
25%     -0.000141  -1.000000  
50%     -0.000024  -1.000000  
75%      0.000042   1.000000  
max      0.000284   1.000000

In [70]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import KFold, cross_val_score

del df['Number']
for column in df.columns:
    if df[column].isnull().values.any():
        print(column)
X = df.values.tolist()
# make Adaboost withh 500 tree
clf = AdaBoostClassifier(n_estimators=500, random_state=0)
# make Kfold with k = 5
cv = KFold(n_splits=5, random_state=1, shuffle=True)
# find accuracy by cross val
accuracy = cross_val_score(clf, X, label, scoring='accuracy', cv=cv, n_jobs=-1)

print(f"accuracy: {mean(accuracy)}")
recall = cross_val_score(clf, X, label, scoring='recall', cv=cv, n_jobs=-1)
print(f"recall: {mean(recall)}")
f1 = cross_val_score(clf, X, label, scoring='f1', cv=cv, n_jobs=-1)
print(f"f1 : {mean(f1)}")

accuracy: 0.7428571428571429
recall: 0.7333333333333333
f1 : 0.6742857142857143


In [71]:
accuracy


array([0.71428571, 0.85714286, 0.71428571, 0.85714286, 0.57142857])

In [72]:
recall

array([0.5       , 1.        , 1.        , 0.5       , 0.66666667])

In [73]:
f1


array([0.66666667, 0.8       , 0.66666667, 0.66666667, 0.57142857])

In [74]:

clf = AdaBoostClassifier(n_estimators=500, random_state=0)
# make Kfold with k = 7
cv = KFold(n_splits=7, random_state=1, shuffle=True)
accuracy = cross_val_score(clf, X, label, scoring='accuracy', cv=cv, n_jobs=-1)


print(f"accuracy: {mean(accuracy)}")
recall = cross_val_score(clf, X, label, scoring='recall', cv=cv, n_jobs=-1)
print(f"recall: {mean(recall)}")
f1 = cross_val_score(clf, X, label, scoring='f1', cv=cv, n_jobs=-1)
print(f"f1 : {mean(f1)}")

accuracy: 0.7428571428571429
recall: 0.5952380952380951
f1 : 0.6


In [75]:
accuracy


array([0.8, 0.8, 1. , 0.6, 0.8, 0.8, 0.4])

In [76]:
recall

array([0.66666667, 0.5       , 1.        , 1.        , 0.5       ,
       0.        , 0.5       ])

In [77]:
f1

array([0.8       , 0.66666667, 1.        , 0.66666667, 0.66666667,
       0.        , 0.4       ])

In [82]:
clf = AdaBoostClassifier(n_estimators=500, random_state=0)
# make Kfold with k = 10

cv = KFold(n_splits=10, random_state=1, shuffle=True)
accuracy = cross_val_score(clf, X, label, scoring='accuracy', cv=cv, n_jobs=-1)

print(f"accuracy: {mean(accuracy)}")
recall = cross_val_score(clf, X, label, scoring='recall', cv=cv, n_jobs=-1)
print(f"recall: {mean(recall)}")
f1 = cross_val_score(clf, X, label, scoring='f1', cv=cv, n_jobs=-1)
print(f"f1 : {mean(f1)}")

accuracy: 0.75


/home/mehxi/PycharmProjects/project_2/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/mehxi/PycharmProjects/project_2/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


recall: 0.5166666666666666


/home/mehxi/PycharmProjects/project_2/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1599: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
/home/mehxi/PycharmProjects/project_2/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1599: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))


f1 : 0.44666666666666666


In [79]:
accuracy

array([0.75      , 0.5       , 1.        , 0.75      , 0.5       ,
       0.66666667, 1.        , 1.        , 0.66666667, 0.66666667])

In [80]:
recall

array([0.66666667, 0.        , 0.        , 1.        , 1.        ,
       0.        , 1.        , 0.        , 0.5       , 1.        ])

In [81]:
f1


array([0.8       , 0.        , 0.        , 0.66666667, 0.66666667,
       0.        , 1.        , 0.        , 0.66666667, 0.66666667])